name: Build binary

on:
  push:
    branches:
      - "master"

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install packages
      run: |
        sudo apt update
        sudo apt install python-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsdl1.2-dev libsmpeg-dev python-numpy subversion libportmidi-dev ffmpeg libswscale-dev libavformat-dev libavcodec-dev
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install -U pygame pyinstaller
    - name: Build and publish
      run: |
        echo "Building"
        pyinstaller bms-kps.py -F -n bms-kps
        cp sdvx.json dist/
        cp pwan.json dist/
        zip -XT9vDrj ubuntu.zip dist/*
    - name: Upload release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ubuntu.zip
        asset_name: ubuntu.zip
        tag: latest
        overwrite: true
  osx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install brew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    - name: Install dependencies
      run: |
        brew install sdl2 sdl sdl_image sdl_mixer sdl_ttf portmidi
        python -m pip install -U pip
        pip install -U pygame pyinstaller
    - name: Build and publish
      run: |
        echo "Building"
        pyinstaller bms-kps.py -F -n bms-kps
        cp sdvx.json dist/
        cp pwan.json dist/
        zip -XT9vDrj osx.zip dist/*
    - name: Upload release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: osx.zip
        asset_name: osx.zip
        tag: latest
        overwrite: true
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install -U pygame pyinstaller
    - name: Build and publish
      run: |
        echo "Building"
        pyinstaller bms-kps.py -F -n bms-kps
        copy sdvx.json dist/
        copy pwan.json dist/
        zip -XT9vDrj windows.zip dist/*
    - name: Upload release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: windows.zip
        asset_name: windows.zip
        tag: latest
        overwrite: true
