# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Build binary

on:
  push:
    branches:
      - "master"

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install python-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsdl1.2-dev libsmpeg-dev python-numpy subversion libportmidi-dev ffmpeg libswscale-dev libavformat-dev libavcodec-dev
        python -m pip install -U pip
        pip install -U pygame pyinstaller
    - name: Build and publish
      run: |
        echo "Building"
        pyinstaller bms-kps.py -F -n bms-kps
        cp sdvx.json dist/
        cp pwan.json dist/
        zip -XT9vDrj ubuntu.zip dist/*
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Latest Build"
        files: |
          ubuntu.zip
  osx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install -U pygame pyinstaller
    - name: Build and publish
      run: |
        echo "Building"
        pyinstaller bms-kps.py -F -n bms-kps
        cp sdvx.json dist/
        cp pwan.json dist/
        zip -XT9vDrj osx.zip dist/*
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Latest Build"
        files: |
          osx.zip
